name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Runs every day at 08:00 UTC (Adjust as needed)
    - cron: '22 3 * * *'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
        
    - name: Commit updated tournament baseline
      if: failure() # Only run this if the test failed (meaning a new tournament was found)
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *known-tournaments.json
        # Only commit if there are actually changes to prevent errors
        git diff --quiet && git diff --staged --quiet || git commit -m "chore: update known tournaments baseline"
        git push

    # This saves the HTML report and the new visual diffs if the test fails
    - uses: actions/checkout@v4
      if: ${{ !cancelled() }}
    - name: Upload Report & Mismatched Snapshots
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30